plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains:annotations:${annotationsVersion}"
    testImplementation "junit:junit:${junitVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "org.glassfish:javax.json:${javaxJsonVersion}"
}
